---
collections:
  - name: community.docker
    version: 5.0.6
  - name: community.general
    version: 12.3.0
  - name: ansible.posix
    version: 2.1.0
  - name: ansible.utils
    version: 6.0.1
  - name: community.windows
    version: 3.1.0
  - name: chocolatey.chocolatey
    version: 1.5.3
  - name: awx.awx
    version: 24.6.1
  - name: kubernetes.core
    version: 6.3.0
  - name: community.sops
    version: 2.2.7
  - name: community.hashi_vault
    version: 7.1.0
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.6.2
  - name: geerlingguy.docker
  - name: gantsign.oh-my-zsh
  - name: arillso.logrotate
  - name: robertdebock.kubectl
  - name: stefangweichinger.ansible_rclone